import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Container, Grid } from '@mui/material'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Ute Salons</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Grid container xs={12} md={12} sm={12} justifyContent="center" alignItems="center" sx={{ minHeight: "100vh" }}>
            <hi>Welcome to Ute Salon</hi>
          </Grid>
        </div>

        <Grid item sm={12} xs={12} md={12}>
          <Footer style={{ margin: 0 }} />
        </Grid>
      </div>
    </>
  )
}
